language: python
sudo: false
install:
  - pip install -r requirements.txt

script:
  - tox

env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py34
  - TOXENV=pypy
  - TOXENV=memorytest27
  - TOXENV=memorytest34
  - TOXENV=doctest27
  - TOXENV=coverage-pypy
